### ISSUE TITLE
unexpected behaviour 

### ISSUE THREAD

**Issue by ratnanil** [mrjoh3/gallerier#2]
I'm using `gallerier` in combination with `distill` and the output is different from what I expected. Here is the code I used in [this rmd](https://github.com/wieselundco/website/blob/master/_faszination-kleinraubtiere-wuehlmaeuse/117-info-dossier-und-workshop-2/117-info-dossier-und-workshop-2.Rmd):
````
```{r, echo = FALSE}
library(tidyverse)
list.files(path = "gallery", pattern = ".jpg$",full.names = TRUE) %>%
  tibble(src = .) %>%
  gallerier::lightbox_gallery("source", width = 200, display = TRUE)
```
```` 

And here is the result: https://wieselundco.github.io/website/faszination-kleinraubtiere-wuehlmaeuse/117-info-dossier-und-workshop-2/

As you can see, the image preview is rendered nicely, but when you click on an image a vast empty space is created and you have to scroll waaaay done to see a single image aligned with the browser window on the left. I would not have expected so much empty space and also the allignment should be with the rest of the text..

**Comment by mrjoh3** [comment]
Hi @ratnanil 

this behaviour indicates your rmd is not able to find the js and css files. I have been having trouble with this for rmd documents. When the `lightbox_gallery` runs the js and css gets copied into the www folder relative to your document.

For now to make sure the connection is made you can include these lines at the top of your document:

```
<link rel="stylesheet" href="www/lightbox-2-2.11.3/css/lightbox.min.css">
<script src="www/lightbox-2-2.11.3/js/lightbox.min.js"></script>
```
or you can use the inline helper function:

`lightbox_rmd()`

**Comment by ratnanil** [comment]
this solved it, thanks!

**Comment by ratnanil** [comment]
however, `lightbox_rmd()` is not and exported function
